name: Build and Release Workflow

on:
  push:
    branches:
      - master  # Cambia a tu rama principal (main, master, etc.)

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [21]  # Versión LTS actual de Java
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build and test
        run: ./gradlew build

      - name: Capture build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Historial completo

      - name: List files for debugging
        run: ls -la

      - name: Release with release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: simple
          include-component-in-tag: false

      - name: Crear release con versión específica
        run: |
          gh release create "v1.21.4" \
            --title "v1.21.4 Release" \
            --notes "Added Gemini command /gemini <prompt>\n"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download build artifacts
        if: success()
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

      - name: List downloaded files (debug)
        run: ls -R build/libs/

      - name: Upload JAR files to release
        run: |
          gh release upload "v1.21.4" build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
